-- FINAL 3.3 - Auditoria opcional
-- Execute no SQL Editor do Supabase somente após revisar.

create table if not exists public.logs_auditoria (
    id bigint generated by default as identity primary key,
    tabela text not null,
    operacao text not null,
    registro_id text,
    usuario_id uuid default auth.uid(),
    dados_anteriores jsonb,
    dados_novos jsonb,
    criado_em timestamptz not null default now()
);

alter table public.logs_auditoria enable row level security;

drop policy if exists "administradores leem auditoria" on public.logs_auditoria;
create policy "administradores leem auditoria"
on public.logs_auditoria for select
to authenticated
using (
    exists (
        select 1 from public.perfis
        where perfis.id = auth.uid()
          and perfis.cargo::text = 'administrador'
    )
);

create or replace function public.registrar_auditoria()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.logs_auditoria (
        tabela, operacao, registro_id, dados_anteriores, dados_novos
    ) values (
        tg_table_name,
        tg_op,
        coalesce(new.id::text, old.id::text),
        case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
        case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
    );
    return coalesce(new, old);
end;
$$;

-- Ative apenas nas tabelas desejadas.
drop trigger if exists auditoria_vendas on public.vendas;
create trigger auditoria_vendas
after insert or update or delete on public.vendas
for each row execute function public.registrar_auditoria();

drop trigger if exists auditoria_caixas on public.caixas;
create trigger auditoria_caixas
after insert or update or delete on public.caixas
for each row execute function public.registrar_auditoria();

drop trigger if exists auditoria_movimentacoes on public.caixa_movimentacoes;
create trigger auditoria_movimentacoes
after insert or update or delete on public.caixa_movimentacoes
for each row execute function public.registrar_auditoria();
